# DockerFile for a Shingle development container

# Use a Xenial base image
FROM ubuntu:xenial

# This DockerFile is looked after by
MAINTAINER Adam Candy <contact@shingleproject.org>

# Install required packages
RUN apt-get update && apt-get install -y \
        git \
        gcc \
        g++ \
        build-essential \
        libnetcdf-dev \
        netcdf-bin \
        python-setuptools \
        python-dev \
        python-pip \
        python-scipy \
        python-numpy \
        python-matplotlib \
        python-shapely \
        python-pyproj \
        python-gdal \
        gdal-bin \
        python-imaging \
        gmsh \
        python-py \
        python-netcdf4 \
        libgeos-c1v5 \
        libgeos-3.5.0 \
        libgeos-dev \
        wget

# Upgrade pip
RUN pip install -i https://pypi.python.org/simple/ --upgrade pip setuptools

# Install ScientificPython
RUN pip install --force-reinstall --ignore-installed --no-binary --no-cache-dir --no-binary :all: ScientificPython

# Update dap and shapely with recent versions
RUN pip install Pydap==3.2.1
RUN pip install -U geos
RUN pip install --no-binary :all: Shapely==1.5.9

# Set build compiler environment 
ENV CC=gcc

# Add a user
RUN adduser --disabled-password --gecos "" shingle
USER shingle
WORKDIR /home/shingle

# Make a copy of the project Shingle
RUN git clone "https://github.com/${REPO}"
WORKDIR /home/shingle/Shingle
RUN git checkout "$BRANCH"
RUN git pull


ENV PATH /home/shingle/Shingle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN make

