# DockerFile for a Shingle development container

# Use a Trusty base image
FROM ubuntu:trusty

# This DockerFile is looked after by
MAINTAINER Adam Candy <contact@shingleproject.org>

# Install required packages
RUN apt-get update && apt-get install -y \
        git \
        gcc \
        g++ \
        build-essential \
        python-setuptools \
        python-dev \
        python-pip \
        python-scipy \
        python-numpy \
        python-scientific \
        python-matplotlib \
        python-shapely \
        python-pyproj \
        python-gdal \
        gdal-bin \
        python-pil \
        gmsh \
        python-pytest \
        curl \
        wget

# Upgrade pip
RUN pip install -i https://pypi.python.org/simple -U pip distribute setuptools

# Update dap and shapely with recent versions
RUN pip install Pydap==3.2.1
RUN pip install Shapely==1.5.9

# Set build compiler environment 
ENV CC=gcc

# Add a user
RUN adduser --disabled-password --gecos "" shingle
USER shingle
WORKDIR /home/shingle

# Make a copy of the project Shingle
RUN git clone https://github.com/adamcandy/Shingle.git
WORKDIR /home/shingle/Shingle
RUN git checkout master
RUN git pull

ENV PATH /home/shingle/Shingle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN make

