#!/usr/bin/env python
# -*- coding: utf-8 -*-

##############################################################################
#
#  Copyright (C) 2011-2018 Dr Adam S. Candy and others.
#  
#  Shingle:  An approach and software library for the generation of
#            boundary representation from arbitrary geophysical fields
#            and initialisation for anisotropic, unstructured meshing.
#  
#            Web: http://www.shingleproject.org
#  
#            Contact: Dr Adam S. Candy, contact@shingleproject.org
#  
#  This file is part of the Shingle project.
#  
#  Please see the AUTHORS file in the main source directory for a full list
#  of contributors.
#  
#  Shingle is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Shingle is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#  
#  You should have received a copy of the GNU Lesser General Public License
#  along with Shingle. If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

import os
import sys
#for path in ['~/bin/common/shingle/']: sys.path.append(os.path.expanduser(path))

try:
    import colored_traceback.auto
except ImportError:
    pass

shingle_path = os.path.realpath(os.path.join(os.path.realpath(os.path.dirname(os.path.realpath(__file__))), os.path.pardir))
sys.path.insert(0, shingle_path)

# Temporarily ignore future warnings, for now
import warnings
warnings.simplefilter(action = "ignore", category = FutureWarning)

import shingle
from shingle import Prime
from shingle.Version import version

__version__ = version
__author__ = 'Adam S. Candy'
__license__ = 'GPL3'

if __name__ == "__main__":
    stat = Prime.main()
    if stat:
        sys.exit(0)
    else:
        sys.exit(1)

